name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DOPPLER_SECRET: $DOPPLER_AUTH

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install CLI
      uses: dopplerhq/cli-action@v1
    - name: inject secrets
      run: doppler secrets substitute settings.toml > settings.toml
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --bin server -v
