name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Install CLI
      uses: dopplerhq/cli-action@v1
    - name: setup doppler token
      run: export DOPPLER_SECRET=$DOPPLER_AUTH
    - name: inject secrets
      run: doppler secrets substitute settings.toml > settings.toml
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
